### ISSUE TITLE
Update to futures 0.3 / future-preview

### ISSUE THREAD

**Issue by marcelbuesing** [oefd/tokio-socketcan#1]
I think it would be great to be able to use this with async/await (once in stable or on the current nightly) without`compat()`.

**Comment by marcelbuesing** [comment]
Started some work here: https://github.com/marcelbuesing/tokio-socketcan/tree/futures-preview compiles, but still has runtime errors. Not sure what the correct way is regarding `PollEvented2`` I assume there is some way to not depend on `tokio-net` or `tokio` altogether.

**Comment by oefd** [comment]
I absolutely intend to get this updated for the new futures! I've mostly been waiting on being able to get it in stable as I mainly use this library in a system I want to keep on stable, but thanks for looking into it in advance.

This weekend there's a good chance I'll look into it on nightly since you already have some stuff I can look at. Not needing tokio is also something I was hoping to sort out because in theory at least a `mio-socketcan` ought to be quite workable.

**Comment by andresv** [comment]
Tokio 0.2 support would be absolute killer.

**Comment by marcelbuesing** [comment]
Closed by #2 , released with crate version `0.2.0`
